### ISSUE TITLE
不知道是否与其它插件冲突，移动功能无效

### ISSUE THREAD

**Issue by chenxin0397** [farux/obsidian-auto-note-mover#10]
![image](https://user-images.githubusercontent.com/73974352/153990184-b3cadaa0-766c-4762-8ce7-6a3bcc38af2a.png)
![image](https://user-images.githubusercontent.com/73974352/153990262-6d43767d-fb0c-41a5-92be-ef4bab236c1d.png)
生成的新笔记还是在/目录下

**Comment by farux** [comment]
Hi. If the note is in the root of the vault, try deleting the empty line in the Exclude Folder setting.
An empty line in the Exclude folder means the root of the vault.
Also, check that the rule does not contain any extra blank spaces.

**Comment by chenxin0397** [comment]
你好，我发现问题的原因了，就是因为“排除文件夹”一项中的是空着的，我在那一项里面填入两个问号问题就解决了。
顺便提一下，您是否可以在默认情况下用几个字符使那一行不空白？这样子问题也就解决了。

**Comment by farux** [comment]
OK, Changed the exclude folder setting in v1.0.9 so that blanks are not treated as root.

**Comment by chenxin0397** [comment]
thanks
