### ISSUE TITLE
Files in root folder cannot be moved

### ISSUE THREAD

**Issue by emisjerry** [farux/obsidian-auto-note-mover#11]
Files in toot folder which match rules cannot be move to specified filder.

BTW, i've made a YouTube video to introduce your plugin, maybe you'll be intrested: https://youtu.be/_253cwqF1aM

**Comment by farux** [comment]
Try deleting the empty line in the Exclude Folder setting. An empty line in the Exclude folder means the root of the vault.
Thanks for letting me know. I'll be watching.

**Comment by farux** [comment]
Changed the exclude folder setting in v1.0.9 so that blanks are not treated as root.
