### ISSUE TITLE
allow to exclude notes in the Templates folder from moving

### ISSUE THREAD

**Issue by erazlogo** [farux/obsidian-auto-note-mover#13]
Hi,
A great plugin, thank you! Would it be possible to add a preference to exclude notes in a particular folder from moving? The Templates folder would contains templates for a particular type of note, including the tags used in the moving rules. But I would not want the template note moved automatically if I edit it.
Thanks!
Elena

**Comment by farux** [comment]
Hi. The latest version has an exclude folder setting. 
You can install and update directly from Obsidian.

**Comment by erazlogo** [comment]
That's great, thanks!
