### ISSUE TITLE
Feature Request: Support YAML Tags

### ISSUE THREAD

**Issue by brimwats** [farux/obsidian-auto-note-mover#2]
I only use `tag: [foo, bar]` in YAML for tagging, so I'd like if I could move based on thoe tags.

**Comment by farux** [comment]
Hi, ANM can recognize both tags in the YAML frontmatter and tags in the body.
The only thing that obsidian declares that it recognizes is `tags`, but I don't know if it recognizes `tag`.

**Comment by brimwats** [comment]
ah great! seems like it's a moot FR then—already does what I wanted and I didn't notice! closing this :)
