### ISSUE TITLE
what happend if two tags match two move rules in a file?

### ISSUE THREAD

**Issue by shuivin** [farux/obsidian-auto-note-mover#21]
# Rule 1. 
tags name "todo", move to folder named "I000-Inbox"
# Rule 2.
tags name "office", move to folder named "O000-Office"

# then :
create a file with tag "todo" and "office", what happend?

**Comment by farux** [comment]
As explained in the README, notes are moved according to the first matching rule.
If the list of rules is sorted numerically, the note will be moved to the destination folder of Rule1.

**Comment by shuivin** [comment]
thanks for your patient explain . 

Got it from readme .
> The rules are checked in order from the top. The notes will be moved to the folder with the first matching rule.

close the issue . please.
