### ISSUE TITLE
Excluded folders doesn't work intuitively

### ISSUE THREAD

**Issue by dummifiedme** [farux/obsidian-auto-note-mover#22]
I had an exclusion rule to avoid auto move of files in "Personal/Journal" but when the files were in "Personal/Journal/2022", they were moved automatically into "Personal". (The move rule was to move all the files tagged with #personal into "Personal') 

Ideally it should touch any file in the "Personal/Journal".

I had to manually apply exclusion for all the folders inside the "Personal/Journal" which is not intuitive. We could have regex or something...I tried `Personal/Journal/*` as well, didn't work.

Please fix this issue. Would benefit everyone

![image](https://user-images.githubusercontent.com/68785729/163663465-fe088e7d-b94a-4f77-8b10-476d4ac45742.png)

**Comment by farux** [comment]
Added regular expression option for excluded folders in v1.2.0.
It should work with the option enabled and `^Personal/Journal/`

**Comment by dummifiedme** [comment]
I have been trying it and it is not working :(

It keeps moving my files I intend not to move, kept in the folder which is excluded.

Does it work on your end?

EDIT: I had missed the newly added toggle. My bad. 


Thanks a lot :)
