### ISSUE TITLE
BUG: When use tag wrangler to change all the matched tags cannot move all of them

### ISSUE THREAD

**Issue by Quorafind** [farux/obsidian-auto-note-mover#4]
It will move only one of them when use tag wrangler to change the matched tags in all files.

**Comment by Quorafind** [comment]
Maybe use dataview to query all the files with matched tags will be a good way to move all files

**Comment by farux** [comment]
Hello @Quorafind  I was currently using `app.metadataCache.on('changed')` as editing event handler.
If I use `app.vault.on('modify')` in addition to it, it seems to catch the changes made by tag wrangler.
It worked in a simple test. 
If it looks ok, I'll add the feature.

**Comment by Quorafind** [comment]
> Hello @Quorafind I was currently using `app.metadataCache.on('changed')` as editing event handler. If I use `app.vault.on('modify')` in addition to it, it seems to catch the changes made by tag wrangler. It worked in a simple test. If it looks ok, I'll add the feature.

Yes, I think this will work, would you want to add this?

**Comment by farux** [comment]
With the help of @pjeby, the author of tag wrangler, this problem was solved in 1.0.4.
