### ISSUE TITLE
Feature Suggest: Automatic Delay

### ISSUE THREAD

**Issue by brimwats** [farux/obsidian-auto-note-mover#5]
Hello!

I use a rather complicated templater script to make new notes—it creates a note, names a note, applies a template. I'd then like auto-note-move to move based on the tag, but there's no way to make it "delayed automatic"

**Comment by farux** [comment]
I think the delay you need will vary from case to case. Can't you just use a manual trigger temporarily?

**Comment by brimwats** [comment]
i can! just was thinking about the templater delay option so thought i'd suggest it!
