### ISSUE TITLE
Automating Subtag Movement with Auto Note Mover

### ISSUE THREAD

**Issue by szfkamil** [farux/obsidian-auto-note-mover#55]
I need help using the Auto Note Mover to move all notes with the tag `people` and its subtags (e.g. `people/family`) to the folder `People`. As it stands, I have to add each subtag individually, so I'm looking for a way to move all subtags at once.

**Comment by ecarrara** [comment]
Hi @szfkamil 

You can do that if you enable the option "Use regular expression to check for tags". `^#people/.*$`
