### ISSUE TITLE
Feature suggestion: exclude a folder

### ISSUE THREAD

**Issue by brimwats** [farux/obsidian-auto-note-mover#6]
Like lots of people i have a folder that is full of templater templates, (200+). while I could add `AutoNoteMover: disable` to all of them it seems like it would be easier to pick some folders to exclude

**Comment by farux** [comment]
OK, I'll consider it.

**Comment by farux** [comment]
Hi, Excluded folders added in 1.0.7

**Comment by brimwats** [comment]
wonderful!! thanks so much 😄
